name: pnMarket
version: '${version}'
main: ru.privatenull.PnMarketPlugin
api-version: '1.16'
authors: [ privatenull ]
description: pnMarket - AuctionPlugin
website: https://github.com/pnFolder/pnMarket
depend: [ProtocolLib]
softdepend: [Vault, PlayerPoints, ExcellentEconomy]
libraries:
  - org.xerial:sqlite-jdbc:3.46.1.3
commands:
  pnmarket:
    description: Панель администратора pnMarket
    aliases: [market, pnm]
    usage: /pnmarket [machine|reload]
    permission: pnmarket.admin
  dah:
    description: Команда для открытия аукциона pnMarket
  ah:
    description: Команда для открытия аукциона pnMarket
permissions:
  pnmarket.sell.auto:
    description: Автоматически рассчитывать цену лота через /ah sell auto
    default: false
  pnmarket.admin:
    description: Управление pnMarket и уведомления об обновлениях
    default: op
